// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class RacketReview
{
    public int ReviewId { get; set; }

    public int RacketId { get; set; }

    public int UserId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Racket Racket { get; set; }

    public virtual User User { get; set; }
}